#ifndef __ERROR_H__
#define __ERROR_H__

#define SUCCESS 							0
#define PORT_OPENED_ERROR    				-1
#define PORT_DEVICE_ERROR					-2
#define PORT_SETCOMM_ERROR					-3
#define PORT_NOTOPEN_ERROR	     			-4
#define PORT_PURGECOMM_ERROR	     		-5
#define PORT_GETCOMTIMEOUT_ERROR			-6
#define PORT_SETCOMTIMEOUT_ERROR			-7
#define PORT_GETCOMMSTATE_ERROR				-8
#define PORT_SETCOMMSTATE_ERROR				-9
#define PORT_CREATEWRITEEVENT_ERROR			-10
#define PORT_CLOSEHANDLE_ERROR				-11
#define PORT_NOTWRITEPENDING_ERROR			-12
#define PORT_WRITEOVERLAPPED_ERROR			-13
#define PORT_WRITETIMEOUT_ERROR				-14
#define PORT_WRITEWAITOBJECT_ERROR			-15
#define PORT_CREATEREADEVENT_ERROR			-16
#define PORT_NOTREADPENDING_ERROR			-17
#define PORT_READOVERLAPPED_ERROR			-18
#define PORT_READTIMEOUT_ERROR				-19
#define PORT_READWAITOBJECT_ERROR			-20
#define PORT_WRITEFILE_ERROR					-21
#define PORT_READFILE_ERROR					-22
#define PORT_LOG_ERROR						-23
#define DONGLE_CONFIRM_ADDVALUE_ERROR		-24
#define DONGLE_CONFIRM_CANCELADDVALUE_ERROR	-25
#define DONGLE_CONFIRM_CARDSALE_ERROR		-26
#define DONGLE_CONFIRM_CANCELCARDSALE_ERROR	-27
#define DONGLE_BLOCKCARD_NOT_FIND			-28
#define DONGLE_CHDIR_ERROR     				-29
#define DONGLE_OPENFILE_ERROR     			-30
#define DONGLE_FSEEK_ERROR     		    	-31
#define DONGLE_FERROR_ERROR     		    -32
#define DONGLE_NO_BLACKLISTR     		    -33
#define DONGLE_PARGUMENTS_ERROR    		    -34
#define DONGLE_MALLOC_ERROR    		        -35
#define DONGLE_CAN_NOT_REQUEST_ERROR		-36

#define NAD_PCB_ERROR			0x6005
#define EDC_ERROR			0x6004
#define REQUEST_NOT_OK			0x60A1//1.0.5.6
#define REQUEST_DIFFERENT		0x60A2//1.0.5.6
#define DATA_ERROR	    0x6088

#endif
